config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/whitelabel-marketplace:
      branch: master
      repo: https://github.com/cyfronet-fid/whitelabel-marketplace
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/whitelabel-marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.indigo_visionary_rabbit.sh
        container: qc.acc_sapphire_warm_kiwi
  QC.Doc:
    repos:
      github.com/cyfronet-fid/whitelabel-marketplace find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ivory_friendly_chameleon.sh
        container: qc.doc_orchid_authentic_gerbil
      github.com/cyfronet-fid/whitelabel-marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.orange_methodical_quokka.sh
        container: qc.doc_pink_sincere_ferret
      github.com/cyfronet-fid/whitelabel-marketplace markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.viridian_affectionate_albatross.sh
        container: qc.doc_taupe_compassionate_mongoose
  QC.Lic:
    repos:
      github.com/cyfronet-fid/whitelabel-marketplace licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunset_dedicated_penguin.sh
        container: qc.lic_snow_ambitious_jackal
  QC.Sty:
    repos:
      github.com/cyfronet-fid/whitelabel-marketplace hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.silver_lucky_uakari.sh
        container: qc.sty_bluebell_graceful_crane
      github.com/cyfronet-fid/whitelabel-marketplace jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.turquoise_creative_goat.sh
        container: qc.sty_dawn_alert_walrus
      github.com/cyfronet-fid/whitelabel-marketplace rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.indigo_compassionate_pelican.sh
        container: qc.sty_onyx_amiable_orangutan
  QC.Ver:
    repos:
      github.com/cyfronet-fid/whitelabel-marketplace get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuchsia_confident_spider.sh
        container: qc.ver_champagne_kind_koala
timeout: 5400
